### ISSUE TITLE
reCAPTCHA breaks import of experiments created with previous versions

### ISSUE THREAD

**Issue by Aldehydi** [lochhh/e-Babylab#2]
Because in the new reCAPTCHA version some code changed in the "persönliche Angaben" html template, (imported) experiments created with previous versions throw an "invalid reCAPTCHA" when submitting the "persönliche Angaben" form. Please document the changes that need to be made to the template of existing experiments. Thank you :)

**Comment by lochhh** [comment]
Thank you @Aldehydi.
I have now updated the README file with the steps that need to be taken to resolve the "invalid reCAPTCHA" issue in the participant form.
