### ISSUE TITLE
quesiton: cannot download data

### ISSUE THREAD

**Issue by piekomk** [lochhh/e-Babylab#5]
Dear Developer,
Thank you for developing such wonderful software. I am a researcher in infant studies and have recently started organizing a research group. Our members are interested in conducting surveys and both moderated and unmoderated experiments with infants and their caregivers in Japan.
Since we are from different universities, we launched a server using a commercial VPS service and have just installed your e-babylab software. It works smoothly, except that we cannot download experiment data. When we try to do so, the browser displays an 'Internal server error (500)' message.
We have read the troubleshooting guide you provided and made sure that the 'webcam' directory is placed in the same directory as 'ipl'. However, we still encounter the same error message.
Can we resolve this issue? We would greatly appreciate any advice or suggestions you could offer.
We understand that you are busy, and we truly appreciate your time and assistance in resolving this issue.

our environment:
Ubuntu 22.04.4 LTS

**Comment by piekomk** [comment]
Hi,

I wanted to follow up on the issue I reported earlier about not being able to download experiment data. 
After digging a bit, I found that changing a line in `./ipl/experiments/reporter.py` fixed the problem. Specifically:
writer.save()
needed to be changed to:
writer.close()

After this modification, I was able to download the experiment data without any Internal Server Errors.
I'm not entirely sure if this is the best solution, but it's working for us now. I thought it might be helpful to share this in case others encounter a similar issue.

Thanks again for developing this great tool. It's really making a difference in our research.

**Comment by lochhh** [comment]
Hi @piekomk thank you very much for raising and suggesting a fix for this issue! You're absolutely right about the need to change `writer.save()` to `writer.close()` as the former is indeed [deprecated](https://pandas.pydata.org/pandas-docs/version/1.5.0/reference/api/pandas.ExcelWriter.save.html). I will push the fix next week when I'm back from vacation. Thank you once again.

**Comment by lochhh** [comment]
Fixed in a000ae240496d3e41ad55176893bfc63a1ff0aeb
